name: Web

on: workflow_dispatch

env:
  Target_tag: v1.7.4
  #Tag want to build.

jobs:
  release:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: v1.7.4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build:prod
      
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test

      - name: he app
        uses: edgarrc/action-7z@v1
        with:
          args: 7z -mx=9 -myx=9 -m0=LZMA2:d=512m:fb=256:mc=256:lc=4 -ms=1t -mmt=1 -ssw -mmemuse=8g a -t7z build.7z ./build/

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          name: Web
          make_latest: true
          files: build.7z
          tag_name: $Target_tag