name: Build/Web
on:
  push:
    tags:
      - "*"


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
        uses: edgarrc/action-7z@v1
      - name: 7zip
        with:
          args: 7z a -mx=9 -myx=9 -m0=LZMA2:d=512m:fb=256:mc=256:lc=4 -ms=1t -mmt=1 -ssw -mmemuse=8g a -r -t7z build.7z ./build/
      - name: Upload releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build.7z"
          bodyFile: "body.md"
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}      